spring:
  redis:
    host: 127.0.0.1
    password: owlIM123
    port: 16379
    database: 0
  data:
    mongodb:
      uri: mongodb://owlIM:owlIM123@mongo:27017/owlim_v1
      database: owlim_v1
update:
  path: /opt/owl/update/
send:
  msg:
    url: http://127.0.0.1:10002
